#!/bin/bash
# =============================================================================
# lib/output.sh — Generates the self-contained restore script and README
#                 written into every completed backup folder on USB.
#
# NOTE: generate_restore_script() contains a large heredoc that IS the
# restore script. Variables are intentionally expanded at generation time
# (no single quotes on the heredoc delimiter) so the generated script is
# fully self-contained.
# =============================================================================

# -----------------------------------------------------------------------------
# RESTORE SCRIPT
# -----------------------------------------------------------------------------

generate_restore_script() {
    local dest="$FINAL_DIR/proxmox-restore.sh"

    # Snapshot config values into local vars. These are expanded into the
    # heredoc below so the generated script is fully self-contained.
    local snap_version="$SCRIPT_VERSION"

    cat > "$dest" << RESTORE_SCRIPT
#!/bin/bash
# =============================================================================
# Proxmox Restore Script
# Auto-generated by PABS v${snap_version} on $(date '+%Y-%m-%d') from $(hostname)
#
# Run this on a FRESH Proxmox install to restore configs from this backup.
# Read through the whole script before executing — not every section applies.
#
# Usage:
#   chmod +x proxmox-restore.sh
#   ./proxmox-restore.sh [--dry-run] [--section SECTION]
#
# Sections: configs | vms | cron | firewall | ssh | packages | scripts | vm-agents
# With no arguments: all sections run with interactive prompts.
# =============================================================================

set -euo pipefail

BACKUP_DIR="\$(cd "\$(dirname "\$0")" && pwd)"
DRY_RUN=false
ONLY_SECTION=""

while [[ \$# -gt 0 ]]; do
    case "\$1" in
        --dry-run)  DRY_RUN=true;         shift   ;;
        --section)  ONLY_SECTION="\$2";  shift 2 ;;
        *)          echo "Unknown argument: \$1"; exit 1 ;;
    esac
done

log()     { echo "[\$(date '+%Y-%m-%d %H:%M:%S')] \$*"; }
run()     { \$DRY_RUN && echo "  [DRY-RUN] \$*" || "\$@"; }
confirm() {
    [[ -n "\$ONLY_SECTION" ]] && return 0
    read -r -p "\$1 [y/N] " reply
    [[ "\${reply,,}" == "y" ]]
}

[[ \$EUID -eq 0 ]] || { echo "Run as root."; exit 1; }
\$DRY_RUN && log "DRY-RUN mode — no changes will be made"

# ---------------------------------------------------------------------------
# Always verify integrity first
# ---------------------------------------------------------------------------
log "=== Verifying backup integrity ==="
if [[ -f "\$BACKUP_DIR/MANIFEST.sha256" ]]; then
    if ( cd "\$BACKUP_DIR" && sha256sum --check MANIFEST.sha256 ); then
        log "✓ All checksums OK"
    else
        log "⚠  Checksum failures detected. Restore with caution."
    fi
else
    log "⚠  No MANIFEST.sha256 found — skipping integrity check"
fi

# ---------------------------------------------------------------------------
# MANDATORY PRE-FLIGHT: Hostname check
# /etc/pve is a FUSE filesystem under nodes/<hostname>/.
# If the hostname on this new machine does not match the backup hostname,
# the cluster service will fail to start with certificate/path errors.
# ---------------------------------------------------------------------------
BACKUP_HOSTNAME="\$(cat "\$BACKUP_DIR/etc/hostname" 2>/dev/null | tr -d '[:space:]')"
CURRENT_HOSTNAME="\$(hostname)"

cat << 'WARN'

╔══════════════════════════════════════════════════════════════════════════╗
║  ⚠  PRE-FLIGHT CHECK — READ BEFORE CONTINUING                          ║
╚══════════════════════════════════════════════════════════════════════════╝

  This script assumes a running Proxmox installation.
  For the full disaster recovery procedure including storage setup,
  read DISASTER-RECOVERY.md FIRST.

WARN

if [[ -n "\$BACKUP_HOSTNAME" && "\$CURRENT_HOSTNAME" != "\$BACKUP_HOSTNAME" ]]; then
    cat << HOSTNAME_WARN

  CRITICAL: Hostname mismatch detected!
    Backup hostname : \$BACKUP_HOSTNAME
    Current hostname: \$CURRENT_HOSTNAME

  /etc/pve/nodes/<hostname>/ holds Node certificates and Node-specific configs.
  A wrong hostname means the cluster service cannot start correctly.

  Fix this NOW, before running any section of this script:
    hostnamectl set-hostname \$BACKUP_HOSTNAME

  Then reboot, or at minimum restart the cluster service:
    systemctl restart pve-cluster

  Aborting. Re-run after correcting the hostname.
══════════════════════════════════════════════════════════════════════════
HOSTNAME_WARN
    exit 1
else
    log "✓ Hostname check: \${CURRENT_HOSTNAME} matches backup (or no backup hostname found)"
fi

# ---------------------------------------------------------------------------
# configs
# ---------------------------------------------------------------------------
if [[ -z "\$ONLY_SECTION" || "\$ONLY_SECTION" == "configs" ]]; then
    log "=== Proxmox configs ==="

    if confirm "Restore /etc/network/interfaces?"; then
        [[ -f "\$BACKUP_DIR/etc/network/interfaces" ]] && \
            run cp -a "\$BACKUP_DIR/etc/network/interfaces" /etc/network/interfaces
        log "✓ Network interfaces restored. Run 'ifreload -a' or reboot to apply."
    fi

    if confirm "Restore /etc/hosts and /etc/hostname?"; then
        [[ -f "\$BACKUP_DIR/etc/hosts" ]]    && run cp "\$BACKUP_DIR/etc/hosts"    /etc/hosts
        [[ -f "\$BACKUP_DIR/etc/hostname" ]] && run cp "\$BACKUP_DIR/etc/hostname" /etc/hostname
    fi

    if confirm "Restore /etc/resolv.conf?"; then
        [[ -f "\$BACKUP_DIR/etc/resolv.conf" ]] && run cp "\$BACKUP_DIR/etc/resolv.conf" /etc/resolv.conf
    fi

    if confirm "Restore APT sources?"; then
        [[ -f "\$BACKUP_DIR/etc/apt/sources.list" ]] && \
            run cp "\$BACKUP_DIR/etc/apt/sources.list" /etc/apt/sources.list
        [[ -d "\$BACKUP_DIR/etc/apt/sources.list.d" ]] && \
            run rsync -a "\$BACKUP_DIR/etc/apt/sources.list.d/" /etc/apt/sources.list.d/
    fi

    if [[ -f "\$BACKUP_DIR/etc-pve.tar" ]]; then
        log "ℹ  /etc/pve is backed up as etc-pve.tar."
        log "   Do NOT extract wholesale onto a live pmxcfs mount."
        log "   Inspect:         tar -tf \$BACKUP_DIR/etc-pve.tar"
        log "   Restore a file:  tar -C / -xf \$BACKUP_DIR/etc-pve.tar etc/pve/storage.cfg"
    fi
fi

# ---------------------------------------------------------------------------
# vms
# ---------------------------------------------------------------------------
if [[ -z "\$ONLY_SECTION" || "\$ONLY_SECTION" == "vms" ]]; then
    log "=== VM and CT definitions ==="
    log "ℹ  VM configs are restore references. VM data is covered by agent bundles (vm-agents/)."
    log "   To rebuild a VM: fresh OS install → deploy agent → restore bundle. See DISASTER-RECOVERY.md."

    [[ -d "\$BACKUP_DIR/vm-ct-definitions/vms" ]] && \
        { log "VM configs:"; ls "\$BACKUP_DIR/vm-ct-definitions/vms"; }
    [[ -d "\$BACKUP_DIR/vm-ct-definitions/containers" ]] && \
        { log "CT configs:"; ls "\$BACKUP_DIR/vm-ct-definitions/containers"; }

    if confirm "Copy raw VM configs to /etc/pve/qemu-server/?"; then
        [[ -d "\$BACKUP_DIR/etc/pve/qemu-server" ]] \
            && run rsync -a "\$BACKUP_DIR/etc/pve/qemu-server/" /etc/pve/qemu-server/ \
            || log "⚠  No raw VM configs in backup."
    fi

    if confirm "Copy raw CT configs to /etc/pve/lxc/?"; then
        [[ -d "\$BACKUP_DIR/etc/pve/lxc" ]] \
            && run rsync -a "\$BACKUP_DIR/etc/pve/lxc/" /etc/pve/lxc/ \
            || log "⚠  No raw CT configs in backup."
    fi
fi

# ---------------------------------------------------------------------------
# cron
# ---------------------------------------------------------------------------
if [[ -z "\$ONLY_SECTION" || "\$ONLY_SECTION" == "cron" ]]; then
    log "=== Cron jobs ==="
    if confirm "Restore cron jobs?"; then
        [[ -f "\$BACKUP_DIR/etc/crontab" ]] && run cp "\$BACKUP_DIR/etc/crontab" /etc/crontab
        [[ -d "\$BACKUP_DIR/etc/cron.d" ]] && run rsync -a "\$BACKUP_DIR/etc/cron.d/" /etc/cron.d/
        [[ -d "\$BACKUP_DIR/var/spool/cron/crontabs" ]] && \
            run rsync -a "\$BACKUP_DIR/var/spool/cron/crontabs/" /var/spool/cron/crontabs/
        log "✓ Cron jobs restored."
    fi
fi

# ---------------------------------------------------------------------------
# firewall
# ---------------------------------------------------------------------------
if [[ -z "\$ONLY_SECTION" || "\$ONLY_SECTION" == "firewall" ]]; then
    log "=== Firewall rules ==="
    if confirm "Restore firewall rules?"; then
        [[ -f "\$BACKUP_DIR/etc/nftables.conf" ]] && run cp "\$BACKUP_DIR/etc/nftables.conf" /etc/nftables.conf
        [[ -d "\$BACKUP_DIR/etc/iptables" ]]      && run rsync -a "\$BACKUP_DIR/etc/iptables/" /etc/iptables/
        [[ -d "\$BACKUP_DIR/etc/pve/firewall" ]]  && run rsync -a "\$BACKUP_DIR/etc/pve/firewall/" /etc/pve/firewall/
        log "✓ Firewall rules restored. Reload with: nft -f /etc/nftables.conf"
    fi
fi

# ---------------------------------------------------------------------------
# ssh
# ---------------------------------------------------------------------------
if [[ -z "\$ONLY_SECTION" || "\$ONLY_SECTION" == "ssh" ]]; then
    log "=== SSH keys ==="
    if confirm "Restore SSH daemon config?"; then
        [[ -f "\$BACKUP_DIR/etc/ssh/sshd_config" ]] && \
            run cp "\$BACKUP_DIR/etc/ssh/sshd_config" /etc/ssh/sshd_config
        [[ -d "\$BACKUP_DIR/etc/ssh/sshd_config.d" ]] && \
            run rsync -a "\$BACKUP_DIR/etc/ssh/sshd_config.d/" /etc/ssh/sshd_config.d/
        log "✓ SSH config restored. Reload with: systemctl reload ssh"
    fi
    if confirm "Restore root SSH keys (/root/.ssh)?"; then
        [[ -d "\$BACKUP_DIR/root/.ssh" ]] && \
            run rsync -a --chmod=D700,F600 "\$BACKUP_DIR/root/.ssh/" /root/.ssh/
        log "✓ Root SSH keys restored."
    fi
fi

# ---------------------------------------------------------------------------
# packages
# ---------------------------------------------------------------------------
if [[ -z "\$ONLY_SECTION" || "\$ONLY_SECTION" == "packages" ]]; then
    log "=== Package state ==="
    PKG_FILE="\$BACKUP_DIR/system-state/dpkg-selections.txt"
    if [[ -f "\$PKG_FILE" ]]; then
        if confirm "Apply dpkg selections? (requires internet for apt-get dselect-upgrade)"; then
            run dpkg --set-selections < "\$PKG_FILE"
            run apt-get -y dselect-upgrade
            log "✓ Packages restored."
        fi
    else
        log "⚠  No package list found."
    fi

    HOLDS_FILE="\$BACKUP_DIR/system-state/apt-holds.txt"
    if [[ -f "\$HOLDS_FILE" && -s "\$HOLDS_FILE" ]]; then
        if confirm "Re-apply held packages?"; then
            while IFS= read -r pkg; do
                [[ -z "\$pkg" ]] && continue
                run apt-mark hold "\$pkg"
            done < "\$HOLDS_FILE"
            log "✓ Package holds restored."
        fi
    fi
fi

# ---------------------------------------------------------------------------
# scripts
# ---------------------------------------------------------------------------
if [[ -z "\$ONLY_SECTION" || "\$ONLY_SECTION" == "scripts" ]]; then
    log "=== Custom scripts ==="
    if confirm "Restore /usr/local/bin?"; then
        [[ -d "\$BACKUP_DIR/usr/local/bin" ]] && run rsync -a "\$BACKUP_DIR/usr/local/bin/" /usr/local/bin/
        log "✓ /usr/local/bin restored."
    fi
    if confirm "Restore /root/scripts?"; then
        [[ -d "\$BACKUP_DIR/root/scripts" ]] && run rsync -a "\$BACKUP_DIR/root/scripts/" /root/scripts/
        log "✓ /root/scripts restored."
    fi
fi

# ---------------------------------------------------------------------------
# vm-agents — restore notes and bundle locations for each backed-up VM/CT
# ---------------------------------------------------------------------------
if [[ -z "\$ONLY_SECTION" || "\$ONLY_SECTION" == "vm-agents" ]]; then
    log "=== VM / LXC agent bundles ==="

    if [[ ! -d "\$BACKUP_DIR/vm-agents" ]]; then
        log "No VM agent bundles in this backup."
    else
        log "Agent bundles found:"
        for bundle_dir in "\$BACKUP_DIR/vm-agents"/*/; do
            [[ -d "\$bundle_dir" ]] || continue
            label="\$(basename "\$bundle_dir")"
            bundle_file="\$(find "\$bundle_dir" -maxdepth 1 -name '*.tar.zst' | head -1)"
            notes_file="\$bundle_dir/restore-notes.txt"

            log ""
            log "  ── \$label ──"

            if [[ -f "\$notes_file" ]]; then
                log "  Restore notes:"
                sed 's/^/    /' "\$notes_file"
            fi

            if [[ -n "\$bundle_file" ]]; then
                log "  Bundle: \$bundle_file"
                log "  Inspect contents:  tar -tf \"\$bundle_file\""
                log "  Extract to /tmp:   tar -C /tmp -xf \"\$bundle_file\""
            else
                log "  ⚠  No .tar.zst bundle found in \$bundle_dir"
            fi
        done

        log ""
        log "ℹ  Each bundle is self-contained. No PABS installation is required on the"
        log "   recovery machine — just tar and the restore-notes.txt inside each bundle."
    fi
fi

log "=== Restore complete ==="
log "Review system-state/ for disk layout, ZFS info, and version notes before rebooting."
RESTORE_SCRIPT

    chmod +x "$dest"
    log "  ✓ Restore script generated"
}

# -----------------------------------------------------------------------------
# README
# -----------------------------------------------------------------------------

generate_readme() {
    cat > "$FINAL_DIR/README.txt" << EOF
Proxmox USB Backup — $DATE
Generated by PABS v${SCRIPT_VERSION} on $(hostname)
Proxmox: $(pveversion 2>/dev/null | head -1 || echo "unknown")
======================================================

CONTENTS
--------
  etc/                    — System configs (/etc/network, /etc/ssh, etc.)
  etc-pve.tar             — Snapshot of /etc/pve (pmxcfs); extract selectively
  vm-ct-definitions/      — qm config / pct config exports for all VMs and CTs
  system-state/           — Disk layout, package lists, kernel, ZFS info
  vm-agents/              — Per-VM/CT agent bundles (Docker, HAOS, Minecraft, generic)
                            Each subdirectory contains a .tar.zst bundle and a
                            restore-notes.txt — no PABS required to restore.
  proxmox-restore.sh      — Interactive restore script (self-contained)
  MANIFEST.sha256         — SHA256 checksums of every file (verified pre-commit)

TO RESTORE
----------
  chmod +x proxmox-restore.sh && ./proxmox-restore.sh
  (add --dry-run to preview; --section NAME for one section only)

  Sections: configs | vms | cron | firewall | ssh | packages | scripts | vm-agents

TO RESTORE A VM AGENT BUNDLE
-----------------------------
  Each bundle under vm-agents/<label>/ is self-contained:
    tar -tf vm-agents/<label>/<label>.tar.zst   # inspect contents
    tar -C /tmp -xf vm-agents/<label>/<label>.tar.zst  # extract
  Read restore-notes.txt inside the bundle for type-specific instructions.

TO VERIFY INTEGRITY
-------------------
  cd <this directory> && sha256sum --check MANIFEST.sha256

IMPORTANT NOTES
---------------
  - VM disk images are NOT included — and not needed. Agent bundles in vm-agents/
    contain the full application state for each VM. To rebuild a VM after a
    hardware failure: fresh OS install → deploy agent (install-agent.sh) → restore
    bundle. See DISASTER-RECOVERY.md for the full step-by-step procedure.
    This script captures config/state so you can rebuild a node quickly.
  - etc-pve.tar: do NOT extract wholesale onto a live Proxmox node. Restore
    individual files with: tar -C / -xf etc-pve.tar etc/pve/storage.cfg
    FUSE sockets were skipped during capture (non-fatal, logged). File-changed
    warnings, if any, indicate the cluster DB was written during the tar pass.
  - MANIFEST.sha256 was verified against local SSD staging BEFORE the USB
    write. A second check ran after transfer. Both results are in backup.log.
  - vm-agents/ bundles may contain sensitive data (API tokens, SSH keys, secrets
    in .env files). The USB stick should be stored securely; anyone with physical
    access to it can read these files.
  - Package restore requires internet access for apt-get dselect-upgrade.
EOF

    log "  ✓ README.txt written"
}

# -----------------------------------------------------------------------------
# DR PLAYBOOK
# Generates DISASTER-RECOVERY.md at backup time from actual system data.
# This file provides a concrete, hostname/version-specific walkthrough
# for recovering from total hardware failure using this backup.
# -----------------------------------------------------------------------------

generate_dr_playbook() {
    local dest="$FINAL_DIR/DISASTER-RECOVERY.md"

    local pve_version
    pve_version=$(head -1 "$FINAL_DIR/system-state/proxmox-version.txt" 2>/dev/null \
        || echo "see system-state/proxmox-version.txt")

    local hostname_at_backup
    hostname_at_backup=$(tr -d '[:space:]' < "$FINAL_DIR/etc/hostname" 2>/dev/null \
        || hostname)

    local backup_date
    backup_date=$(date '+%Y-%m-%d %H:%M')

    cat > "$dest" << EOF
# Disaster Recovery Playbook
> Generated by PABS v${SCRIPT_VERSION} on ${backup_date} from: ${hostname_at_backup}
> Proxmox version at backup time: ${pve_version}

## ⚠ Read this document fully before doing anything.

This playbook covers recovery from **total hardware failure** using this backup.
The agent bundles in \`vm-agents/\` replace vzdump — they contain the full application
state for each VM. You do not need disk images.

---

## Phase 1 — Install Proxmox base

### Step 1: Install Proxmox VE
- Download ISO: https://www.proxmox.com/en/downloads
- Target version: **${pve_version}** (exact version recommended for config compatibility)
- During installation, set hostname to: \`${hostname_at_backup}\`

> **CRITICAL — Hostname:** \`/etc/pve/nodes/<hostname>/\` contains Node certificates,
> subscription info, and Node-specific configs. If the hostname differs from
> \`${hostname_at_backup}\`, certificates and paths will not match and \`pve-cluster\`
> will fail to start correctly.
>
> Verify after install:  \`hostnamectl\`
> Fix if wrong:          \`hostnamectl set-hostname ${hostname_at_backup}\`
> Then restart:          \`systemctl restart pve-cluster\`

### Step 2: Create storage pools
Before running \`proxmox-restore.sh\`, the storage pools referenced in
\`storage.cfg\` must exist. Reference files in \`system-state/\`:

- \`disk-layout-lsblk.txt\` — disk overview
- \`disk-layout-fdisk.txt\` — partition details
EOF

    # ZFS-specific instructions if backed up
    if [[ -f "$FINAL_DIR/system-state/zfs-pool-status-by-id.txt" ]]; then
        cat >> "$dest" << 'EOF'
- `system-state/zfs-pool-status-by-id.txt` — pool topology with stable by-id device paths
- `system-state/zfs-dataset-list.txt` — dataset list

**ZFS pool rebuild example:**
```bash
# Get the exact device paths from zfs-pool-status-by-id.txt, then:
zpool create <poolname> <topology> /dev/disk/by-id/<device1> /dev/disk/by-id/<device2>
# Re-create datasets as needed (see zfs-dataset-list.txt)
```
Use `by-id` paths — `/dev/sda` changes with device insertion order on new hardware.
EOF
    else
        cat >> "$dest" << 'EOF'

> ⚠ **ZFS pool info not in backup** (`BACKUP_ZFS=false` at backup time).
> Pool topology must be reconstructed from memory or from the old hardware.
> Consider setting `BACKUP_ZFS="true"` in config.sh going forward.
EOF
    fi

    # LVM-specific instructions if backed up
    if [[ -f "$FINAL_DIR/system-state/lvm-vgs.txt" ]]; then
        cat >> "$dest" << 'EOF'

**LVM restore (if applicable):**
```bash
# Machine-readable VG configs in system-state/lvm-vg-<name>.cfg
vgcfgrestore -f system-state/lvm-vg-<name>.cfg <vg-name>
```
EOF
    fi

    cat >> "$dest" << 'EOF'

---

## Phase 2 — Restore Proxmox configuration

Proxmox is running, hostname is correct, storage pools exist.

### Step 3: Run the restore script
```bash
chmod +x proxmox-restore.sh
./proxmox-restore.sh
```

Run sections in this order (or let the script run all with prompts):
1. `configs`   — network, hosts, APT sources, /etc/pve
2. `firewall`
3. `ssh`
4. `cron`
5. `packages`
6. `scripts`

### Step 4: Reboot
Reboot before starting the VM rebuild phase.

---

## Phase 3 — Rebuild VMs and LXCs

Each VM must be freshly installed, then populated from its agent bundle.
**Agent bundles replace vzdump** — they contain the full application state.

### Rebuild procedure (per VM):
1. Create a fresh VM/LXC in Proxmox (specs in `vm-ct-definitions/`)
2. Install a base OS
3. Deploy the PABS agent: `./install-agent.sh <user>@<new-ip>`
4. Restore the bundle: see `restore-notes.txt` inside the bundle

EOF

    # Per-VM rebuild hints from backed-up data
    if [[ -d "$FINAL_DIR/vm-agents" ]]; then
        echo "### Agent bundles available:" >> "$dest"
        echo "" >> "$dest"
        for bundle_dir in "$FINAL_DIR/vm-agents"/*/; do
            [[ -d "$bundle_dir" ]] || continue
            local label
            label=$(basename "$bundle_dir")
            echo "#### \`$label\`" >> "$dest"
            echo "- Bundle: \`vm-agents/$label/\`" >> "$dest"
            echo "- VM specs reference: \`vm-ct-definitions/\`" >> "$dest"
            echo "- Restore: inspect \`restore-notes.txt\` inside the bundle" >> "$dest"
            echo "" >> "$dest"
        done
    fi

    if [[ -d "$FINAL_DIR/vm-ct-definitions/vms" ]] || \
       [[ -d "$FINAL_DIR/vm-ct-definitions/containers" ]]; then
        cat >> "$dest" << 'EOF'
### VMs/LXCs without agent bundle (config reference only)
These were backed up without an agent. Configs in `vm-ct-definitions/` show
specs (CPU, RAM, disk sizes, network). OS and data must be freshly installed.

EOF
    fi

    cat >> "$dest" << 'EOF'
---

## Phase 4 — Verification

After full rebuild, check:
- Proxmox WebUI reachable: `https://<hostname>:8006`
- All VMs/LXCs in expected state
- Network bridges correct: `ip link show`
- Storage pools visible: `pvesm status`
- Backup integrity: `cd <this-directory> && sha256sum --check MANIFEST.sha256`
EOF

    # Offsite recovery instructions — only written if rclone was configured
    if [[ -n "${RCLONE_REMOTE:-}" ]]; then
        local encryption_note=""
        if [[ -n "${RCLONE_ENCRYPTION_PASSWORD:-}" ]]; then
            encryption_note="
> **Encrypted remote:** the offsite data was encrypted with rclone crypt.
> You need your \`RCLONE_ENCRYPTION_PASSWORD\` (and \`RCLONE_ENCRYPTION_SALT\` if set)
> to access it. Without these, the offsite data cannot be decrypted.
> Retrieve them from your password manager before proceeding."
        fi

        cat >> "$dest" << EOF

---

## Recovering from offsite (if USB is lost or unavailable)
${encryption_note}

The offsite remote (\`${RCLONE_REMOTE}\`) holds the same backup directories
as the USB stick, named by date (\`YYYY-MM-DD_HH-MM-SS/\`).

### Step 1 — Install rclone and configure the base remote
\`\`\`bash
apt install rclone
rclone config  # re-configure the same remote as on the original host
\`\`\`
EOF

        if [[ -n "${RCLONE_ENCRYPTION_PASSWORD:-}" ]]; then
            cat >> "$dest" << 'EOF'

### Step 2 — Re-create the encryption wrapper
```bash
# Replace <PASSWORD> and <SALT> with your stored credentials.
# Use the same values as on the original host — wrong credentials = unreadable data.
rclone config create pabs_crypt_runtime crypt \
    remote          "<your-base-remote-path>" \
    filename_encryption standard \
    directory_name_encryption true \
    password        "$(rclone obscure '<PASSWORD>')" \
    password2       "$(rclone obscure '<SALT>')"   # omit if no salt was set
```

Access the remote via `pabs_crypt_runtime:` from here on.
EOF
        fi

        cat >> "$dest" << EOF

### Step 3 — Download the backup
\`\`\`bash
# List available backups
rclone lsf "${RCLONE_REMOTE}" --dirs-only

# Download the most recent one (adjust date as needed)
mkdir -p /mnt/restore
rclone copy "${RCLONE_REMOTE}/<YYYY-MM-DD_HH-MM-SS>" /mnt/restore/ --progress
\`\`\`

### Step 4 — Verify and restore
\`\`\`bash
cd /mnt/restore
sha256sum --check MANIFEST.sha256
chmod +x proxmox-restore.sh
./proxmox-restore.sh
\`\`\`
EOF
    fi

    log "  ✓ DISASTER-RECOVERY.md generated"
}
